### ISSUE TITLE
Build -skip to main content

### ISSUE THREAD

**Issue by carlosalbertobuitragosantamaria** [carlosalbertobuitragosantamaria/agency-repo#7]
this is common on sites where menus are populated and using the tab key to navigate through links can take a while before arriving at the main content.
Since our menu bar is very small this is probably not necessary, but it may give us points for having implemented it, besides it's fairly simple. 
In any case we can decide whether we want it or not 

``` html
HTML

<a class='skip-to-main' href='#main'>Skip to Main Content</a>
....
<main id='main'>
...
```

```css
CSS

.skip-to-main {
  transform: translateY(-120%);
  transition: transform 320ms ease-in;
}

.skip-to-main:focus {
  transform: translateY(0);
}

// then add some styling..//
```
